config/routes.rb
Rails.application.routes.draw do
  resources :users do 
    resources :recommendations, only: [:show,:index,:new,:edit,:create,:update,:destroy]
  end
  resources :recommendations, only: [:show,:index,]
  resources :channels, only: [:show]
  root to: 'static#home'
  match '/auth/twitch/callback', to: 'sessions#twitch_login', via: [:get, :post] 
  get 'login', to: 'sessions#new'
  get 'login_twitch', to: 'sessions#new_twitch'
  post 'login', to: 'sessions#create'
  match 'logout', to: 'sessions#destroy', via: [:get, :post]
  get 'new_channel', to: 'static#new_channel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
    has_many :recommendations 
    has_many :users, through: :recommendations

    def to_param
        self.name
    end

    def self.find_or_create_by_name(name)
        if name
            begin
                channel_data = $client.get_users(login: name).data
            rescue Twitch::ApiError
                channel_data = []
            end
            unless channel_data.empty?
                channel = Channel.find_by(name: channel_data[0].display_name)
                channel = Channel.create(
                    name: channel_data[0].display_name,
                    description: channel_data[0].description,
                    profile_image_url: channel_data[0].profile_image_url
                ) unless channel
            end
            channel
        end
    end
end

app/models/filter.rb
class Filter < ApplicationRecord
    belongs_to :user
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
    belongs_to :user
    belongs_to :channel

    validates :content, length: {minimum: 20}

    def channel_name=(name)
        channel = Channel.find_or_create_by_name(name)
        self.channel = channel
    end

    def channel_name 
        self.channel.try(:name)
    end

        
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :recommendations
    has_many :filters
    has_many :channels, through: :recommendations

    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        User.find_by(id: session[:user_id])
    end

    def redirect_if_not_logged_in
        redirect_to root_path, notice: "You must be logged in to see that page." unless logged_in?
    end

    def redirect_if_not_current_user
        redirect_if_not_logged_in
        id = params[:user_id]
        return head(403) unless session[:user_id] == id.to_i
    end

    def redirect_if_already_logged_in
        redirect_to root_path, notice: "You are already logged in." if logged_in?
    end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
    def show
        @channel = Channel.find_or_create_by_name(params[:id]).try(:name)
        flash[:notice] = "No channel found with that name" if @channel.nil?
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
    def index
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @recommendations = @user.recommendations.reverse_order
        else
            @recommendations = Recommendation.all.reverse_order
        end
    end

    def show
        if params[:user_id]
            @user = User.find_by(id: params[:user_id])
            @recommendation = @user.try(:recommendations).find_by(id: params[:id])
        else
            @recommendation = Recommendation.find_by(id: params[:id])
        end
        redirect_to recommendations_path, notice: "We couldn't find that recommendation" if @recommendation.nil?
    end

    def new
        redirect_if_not_current_user
        @user = current_user
        @recommendation = Recommendation.new(channel_name: params[:channel_name])
    end

    def edit
        redirect_if_not_current_user
        @user = current_user
        @recommendation = Recommendation.find_by(id: params[:id])
        redirect_to recommendations_path, notice: "No recommendation found with that ID" if @recommendation.nil?
    end

    def create
        @recommendation = Recommendation.new(recommendation_params)
        if @recommendation.save
            redirect_to recommendation_path(@recommendation)
        else
            @user = current_user
            render 'new'
        end
    end

    def update
        @recommendation = Recommendation.find(params[:id])
        @recommendation.update(recommendation_params)
        if @recommendation.valid?
            redirect_to recommendation_path(@recommendation)
        else
            @user = current_user
            render 'edit'
        end
    end

    def destroy
        redirect_if_not_current_user
        Recommendation.destroy(params[:id])
        redirect_to recommendations_path
    end

    private 

    def recommendation_params
        params.require(:recommendation).permit(:channel_name,:content,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :redirect_if_already_logged_in, except: [:destroy,:create,:twitch_login]
    def new 
        @user = User.new
    end

    def new_twitch
        redirect_to '/auth/twitch'
    end

    def create
        user = User.find_by(name: user_params[:name])
        if user && user.authenticate(user_params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            redirect_to login_path, notice: "No users found with the provided name and password"
        end
    end

    def twitch_login
        user = User.find_or_create_by(twitch_login_params)
        if user.password_digest.nil?
            user.password = rand(36**16).to_s(36) 
            user.save
        end
        session[:user_id] = user.id 
        redirect_to root_path
    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end

    private

    def twitch_login_params
        {
            name: request.env['omniauth.auth'].info.name,
            provider: request.env['omniauth.auth'].provider,
            uid: request.env['omniauth.auth'].uid
        }
    end

    def user_params
        params.require(:user).permit(:password,:name)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home
        @channel = get_random_channel
    end

    def get_random_channel
        streams = $client.get_streams(language:'en', first:100)
        int = rand(10)
        int.times do 
            page = streams.pagination['cursor']
            streams = $client.get_streams(language:'en', first:100, after: page)
        end
        int = rand(100)
        channel = streams.data[int]
        channel ? channel.user_name : get_random_channel
    end

    def new_channel
        @channel=get_random_channel
        render json: {channel: @channel}
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :redirect_if_already_logged_in, only:[:new]
    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id 
            redirect_to root_path
        else
            render 'new'
        end
    end

    private

    def user_params
        params.require(:user).permit(:name,:password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        User.find_by(id: session[:user_id])
    end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_channel.html.erb
<p style="display: none" class="channel"><%= @channel %></p>
<div id="twitch-embed"></div>

<script type="text/javascript">
    new Twitch.Embed("twitch-embed", {
        channel: document.querySelector(".channel").innerText,
        parent: ["localhost", "randomstreamfinder.herokuapp.com"]
    });
</script>

app/views/channels/show.html.erb
<%= render 'channel' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitchTvRandomStreamFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://embed.twitch.tv/embed/v1.js"></script>
    <script type="text/javascript">
      function newChannel(){
        const streamPlayer = document.querySelector("iframe")
        const btn = document.querySelector("#new-stream-button")
        btn.onclick = null 
        btn.style.color = "rgb(32, 32, 32)"
        fetch("http://localhost:3000/new_channel")
          .then(res => res.json())
          .then(json =>{
              streamPlayer.remove()
              new Twitch.Embed("twitch-embed", {
                  channel: json.channel,
                  parent: ["localhost", "randomstreamfinder.herokuapp.com"]
              });
              btn.style.color = 'white'
              btn.onclick = newChannel
          })
          .catch( ()=> {
            btn.style.color = "white"
            btn.onclick = newChannel
          })
      }

        
      function dropdown(){
        const menu = document.querySelector('.hamburger')
        if(menu.style.display === "none"){
          menu.style.display = "block"
        }
        else menu.style.display = "none"
      }
    </script>
  </head>

  <body>
   
  <nav class="navbar navbar-expand" >
    <div class="d-flex top-row-phone navbar-nav">
      <div class= "logo navbar-brand my-auto">Random Stream Finder</div>
        <% if current_page?(root_path) %>
          <li class="nav-item">
            <b><a href="#" onclick="newChannel()" class="nav-link" id="new-stream-button">New Stream</a></b>
          </li>
        <% else %>
          <%= link_to "Home", root_path, class:"nav-link" %>
        <% end %>
          <a href="javascript:void(0);" class="icon nav-icon" onclick="dropdown()">
            <%= image_tag("hambuger_icon.png") %>
          </a>
    </div>

  <ul class = "navbar-nav hideforphone">
    <li class="nav-item">
      <%= link_to "Browse Recommendations", recommendations_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class='nav-item'>
        <%= link_to "Create a Recommendation",
          new_user_recommendation_path(current_user, channel_name: @channel),
          class: "nav-link"
        %>
      </li>
      <li class="nav-item">
        <%= link_to "View Profile Page", user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "logout", logout_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", login_path, class: 'nav-link' %>
      </li>
      <li class = "nav-item">
        <%= link_to "Signup", new_user_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>

  <ul class = "navbar-nav hamburger">
    <li class="nav-item">
      <%= link_to "Browse Recommendations", recommendations_path, class: "nav-link" %>
    </li>
    <% if logged_in? %>
      <li class='nav-item'>
        <%= link_to "Create a Recommendation",
          new_user_recommendation_path(current_user, channel_name: @channel),
          class: "nav-link"
        %>
      </li>
      <li class="nav-item">
        <%= link_to "View Profile Page", user_path(current_user), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "logout", logout_path, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", login_path, class: 'nav-link' %>
      </li>
      <li class = "nav-item">
        <%= link_to "Signup", new_user_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>

<% flash.each do |type, msg| %>
<div class = "alert alert-primary" role = "alert">
  <%= msg %>
</div>
<% end %>
<%= yield %>
</body>

</html>

app/views/recommendations/_form.html.erb
<% if @recommendation.errors.any? %>
    <% @recommendation.errors.full_messages.each do |msg| %>
        <div class = 'alert alert-primary'>
            <%= msg %>
        </div>
    <% end %>
<% end %>

<%= form_for [@user, @recommendation] do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class='form-group'>
        <div><%= f.label :channel_name, class:"text-white font-weight-bold tab" %></div>
        <%= f.text_field :channel_name, placeholder: "The streamer's username; must be exact", class: "form-control"%>
    </div>

    <div class='form-group'>
        <div><%= f.label :content, class:"text-white font-weight-bold tab"%></div>
        <%= f.text_area :content, rows:'10', placeholder: "Describe what you like about this streamer", class: "form-control" %>
    </div>
    <%= f.submit class: 'btn btn-primary tab' %>
<% end %>

    

app/views/recommendations/_recommendations.html.erb
<div class = "d-flex flex-row flex-wrap">
    <% recommendations.each do |rec| %>
        <div class= "p-2 w-25 recommendation-card">
            <div class="d-flex justify-content-center">
                <%=link_to image_tag(rec.channel.profile_image_url,size: "75x75"), channel_path(rec.channel) %>
            </div>
            <div class= "recommendation-text">
                <%= link_to "#{rec.channel.name}'s Recommendation", user_recommendation_path(rec.user,rec),class: "align-top" %>
                <div class= "description"><%= rec.content %></div>
            </div>
        </div>
    <% end %>
</div>

app/views/recommendations/edit.html.erb
<%= render 'form' %>

app/views/recommendations/index.html.erb
<% if @user %>
    <h2> <%= current_user == @user ? "Your" : "#{@user.name}'s" %> Recommendations </h2>
<% end %>
<%= render partial: 'recommendations', locals: {recommendations: @recommendations} %>

app/views/recommendations/new.html.erb
<%= render 'form' %>

app/views/recommendations/show.html.erb
<div class="d-flex justify-content-center">
    <%=link_to image_tag(@recommendation.channel.profile_image_url), channel_path(@recommendation.channel) %>
</div>
<h2 class="text-primary text-center"><%=@recommendation.channel.name%></h2>
<div class = "d-block text-center">
    <p class=" text-light"><%=@recommendation.content%></p>
    <p>Recommended by <%=link_to @recommendation.user.name, user_path(@recommendation.user) %></p>
</div>

<% if @user && @user == current_user %>
    <br>
    <%= link_to "Edit Recommendation", edit_user_recommendation_path(@user,@recommendation) %>
    <%= button_to "Delete Recommendation", user_recommendation_path(@user,@recommendation), method: 'delete' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <div class="form-group">
        <div><%= f.label :name, class: "text-white font-weight-bold tab" %></div>
        <%= f.text_field :name, class: "form-control-lg", placeholder: "username" %>
    </div>

    <div class="form-group">
        <div><%= f.label :password, class: "text-white font-weight-bold tab" %></div>
        <%= f.password_field :password, class: "form-control-lg", placeholder: "password" %>
    </div>

    <%= f.submit "Create Account", class: "btn btn-primary" %>
<% end %>

app/views/users/new.html.erb
<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <div class = 'alert alert-primary'>
            <%= msg %>
        </div>
    <% end %>
<% end %>

<div class = "center-in-page">
    <h2 class: "text-center">Create An Account</h2>
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<h2 class="text-center text-primary"> 
    <%= current_user == @user ? "Your" : "#{@user.name}'s" %> Profile
</h2>

<br>
<div class = "tab">
    <h3>Recommendations</h3>
    <%= render partial: '/recommendations/recommendations', locals: {recommendations: @user.recommendations} %>
</div>

app/views/users/success.html.erb
You Logged In!